apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- capoperator_configMap.yaml
- capapplication_configMap.yaml
- capapplicationversion_configMap.yaml
- captenant_configMap.yaml
- captenantoperation_configMap.yaml
